{{- if .Values.fossbilling.persistence.fossbilling.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    katenary.v3/compose-hash: 9d9192a237ae1cc3996db0750cec787cbc6f027a
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "fossbilling.labels" . | nindent 4 }}
    katenary.v3/component: fossbilling
  name: '{{ include "fossbilling.fullname" . }}-fossbilling-fossbilling'
spec:
  accessModes:
  {{- .Values.fossbilling.persistence.fossbilling.accessMode | toYaml | nindent 2 }}
  resources:
    requests:
      storage: {{ tpl .Values.fossbilling.persistence.fossbilling.size $ }}
  {{- if ne .Values.fossbilling.persistence.fossbilling.storageClass "-" }}
  storageClassName: '{{ .Values.fossbilling.persistence.fossbilling.storageClass }}'
  {{- end }}

{{- end }}