apiVersion: v1
kind: Service
metadata:
  annotations:
    katenary.v3/compose-hash: 9d9192a237ae1cc3996db0750cec787cbc6f027a
    katenary.v3/version: release-3.0.0-rc2
  labels:
    {{- include "fossbilling.labels" . | nindent 4 }}
    katenary.v3/component: fossbilling
  name: '{{ include "fossbilling.fullname" . }}-fossbilling'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "fossbilling.selectorLabels" . | nindent 4 }}
    katenary.v3/component: fossbilling
